# trigger comment
services:
  healthchecker:
    image: ghcr.io/mksmin/api-health-checker:latest
    container_name: healthchecker
    volumes:
      - healthchecker-data:/app/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

volumes:
  healthchecker-data: